### ISSUE TITLE
User SignIn: SignIn application

### ISSUE THREAD

**Issue by k279avi** [onenroll/onenroll.in#5]
As a user, I want to sign-in into the application.

Features:
1. Sign-in form will have user input fields for email and password.
2. Sign-in form should also have social login feature including sign-in using gmail and facebook account.

Considerations:
1. When users submit blank or incomplete form, error should be shown.
2. When users submit incorrect email or password, error should be shown.

**Comment by notamanbag** [comment]
Completed this.
